twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        image_placeholder_path: '/images/image_placeholder.jpg'

when@test:
    twig:
        strict_variables: true
